version: "3.8"

services: # adds 2 services: mysql and phpmyadmin to connect with
#  web:
#    image: quay.io/wildfly/wildfly
#    container_name: wildfly
#    ports:
#        - "8088:8080"
#    volumes:
#      - ./target/cnss-1.0-SNAPSHOT.war:/opt/wildfly/standalone/deployments/cnss-1.0-SNAPSHOT.war
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: always # restart the container if it stops
    environment: # add default values, see docs for more info.
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: macnss
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    container_name: phpmyadmin_cnss
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8084:80"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword #(Required) set the password for the root superuser account.
      PMA_HOST: db   # define the address/hostname of the mysql server e.g. db or mysql  (Required)
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: mypassword # use the root password to login on startup.

volumes: # add persistent data even if container is removed.
  my-db: